version: "3.7"

services:
  karax_tables_csv:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - "../:/app"
    ports:
      - "5000:5000"
    entrypoint:
      "/app/docker/entry_point.sh"